# Generated by Django 4.0.1 on 2022-05-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=25)),
                ('user', models.CharField(max_length=25)),
                ('create_on', models.DateTimeField()),
            ],
        ),
    ]
