# Generated by Django 4.0.1 on 2022-05-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
