# Generated by Django 4.0.1 on 2022-05-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='mail',
        ),
    ]
