# Generated by Django 4.2.1 on 2023-05-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_email_feedback_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('date', models.CharField(default='Date', max_length=25)),
                ('output', models.CharField(default='Close', max_length=25)),
            ],
        ),
    ]
